services:
  furfeastco:
    build: .
    ports:
      - "8080:8080"
    environment:
      DEBUG: "False"
      DJANGO_SETTINGS_MODULE: "FURFEASTCO.settings"
      SECRET_KEY: "django-insecure-u%=m_jym@7l@45gval389byel^zg#%7pian(h3p0j68y90%+q+"
      DEBUG: "False"
      DB_HOST: "34.129.215.28"
      DB_NAME: "furfeast"
      DB_USER: "furfeast-user"
      DB_PASSWORD: "FurfeastDB2024!"
      DB_PORT: "5432"
      EMAIL_HOST_USER: "cofurfeast@gmail.com"
      EMAIL_HOST_PASSWORD: "omylzdzofbxymrxv"
      GS_BUCKET_NAME: "furfeastco-media"
    deploy:
      resources:
        reservations:
          memory: 512M